### ISSUE TITLE
One dot isn't doing is job

### ISSUE THREAD

**Issue by Its-Just-Nans** [taniarascia/sokoban#2]
One of the dots dot doesn't change squares in green

![NAME](https://user-images.githubusercontent.com/56606507/126817515-b5595c7a-5fd2-4855-a448-b2347a1fee16.gif)

Is-it normal ?

**Comment by taniarascia** [comment]
Seems like a regression based on https://github.com/taniarascia/sokoban/pull/1.

@michelc thoughts? Otherwise I might just revert it.
