### ISSUE TITLE
I win the game by moving on a dot myself?

### ISSUE THREAD

**Issue by koraytugay** [taniarascia/sokoban#4]
In this state, if I move left I see the "A Winner is You" Screen..

<img width="967" alt="Screen Shot 2021-07-30 at 8 09 19 PM" src="https://user-images.githubusercontent.com/1974123/127722440-b22ff7c3-7f38-4f31-99e6-54d98eca452a.png">

**Comment by taniarascia** [comment]
Heh yeah, I don't clear the game state when you win so you can keep playing and un-win. Should be an easy fix.

**Comment by koraytugay** [comment]
I think it is not related to game state. I proposed a fix: https://github.com/taniarascia/sokoban/pull/5
Feel free to improve and/or close it. 
Thank you.

**Comment by koraytugay** [comment]
I think I was not successful at explaining the issue. In the state I share in the screenshot - if I move left with player I see the "The winner is you" screen. But I am only covering the cell with the player icon, not with a block. It is not about winning and un-winning I think.

**Comment by cniklas** [comment]
I've noticed that issue, too. Thanks for your fix!

**Comment by koraytugay** [comment]
@cniklas I think a more proper way to fix this is to introduce a new boolean `isPlayerOnVoid` and then adding it to the condition where `isWin` is determined..

**Comment by cniklas** [comment]
> @cniklas I think a more proper way to fix this is to introduce a new boolean `isPlayerOnVoid` and then adding it to the condition where `isWin` is determined..

Right!
